### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by libp** [Ahaochan/Ahaochan.github.io#33]
原文：https://ahaochan.github.io/posts/Travis_CI_Encrypting_Files
评论我写的。
travis encrypt-file命令将使用对称加密 (AES-256) 为你加密文件, 并将密钥存储在secure变量中
怎么拿到这个变量的值呢？
travis CI也没有把 这个值自动同步到travis的变量里

**Comment by Ahaochan** [comment]
先确保travis客户端已登录成功，
执行了`travis encrypt-file`命令后，在`https://travis-ci.org/用户名/项目名/settings`的`Environment Variables`下，会**自动**加上加密的变量。

另外，变量名不是`secure`，一般是随机的，如`encrypted_0a6446eb3ae3_key`和`encrypted_0a6446eb3ae3_iv`

**Comment by libp** [comment]
不知道哪里出了幺蛾子，我登陆成功，然后按照步骤执行命令，这两个变量就是没有自动加上去。非常奇怪，试了很多遍，后面自己指定k iv的值才搞定。你会看encrypted_0a6446eb3ae3_iv保存的值具体是多少吗

**Comment by Ahaochan** [comment]
参见[Travis-CI 加密变量](https://ahaochan.github.io/posts/Travis_CI_Encrypting_keys.html)加密方案部分。
我看不到
